#!/bin/bash
kversion=3.19.0vtcp+

#scp aran@neo:/local_data/aran/$kversion.tar.gz ~

#mkdir $HOME/$kversion
#cd $HOME/$kversion
#mkdir -p lib/modules
src=/local_data/aran/inst/$kversion
sudo rsync -avzr aran@neo:$src/lib/modules/* /lib/modules/
#sudo scp -r aran@neo:/local_data/aran/$kversion/usr/src/* /usr/src/
sudo rsync -avzr aran@neo:$src/System.map-* /boot/
sudo rsync -avzr aran@neo:$src/vmlinuz-* /boot/
sudo rsync -avzr aran@neo:$src/config-* /boot/


#sudo chown root:root *
#sudo cp -a lib/modules/* /lib/modules/
#sudo cp -a usr/src/* /usr/src/
#sudo cp System.map-* /boot/
#sudo cp vmlinuz-* /boot/
sudo update-initramfs -c -k $kversion
sudo update-grub2

#sudo rm -Rf $HOME/$kversion
